- hosts: all
  sudo: yes

  tasks:
  - name: Install Packages
    apt: name={{ item }} update_cache=yes state=present
    with_items:
      - apache2 
      - libapache2-mod-php5
      - git
      - curl


  - name: Git Clone Repo
    git: repo=https://github.com/maniSbindra/spinnaker-packer-ansible-php-azure-demo.git dest=/opt/phpapp update=yes force=yes accept_hostkey=yes 
    register: git_finished

  - name: copy index.php
    sudo: yes
    copy: src=/opt/php/index.php  dest=/var/www/html/index.php mode=644
    notify: Restart Apache


  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted